---
- name: Configure Docker server
  hosts: ec2_webserver
  become: true
  # become_method: sudo
  connection: ssh
  vars:
      pkg_name: docker
      
  tasks:
  - name: Execute the command in remote shell; stdout goes to the specified file on the remote
    ansible.builtin.script: 
      cmd: docker_script.sh > /home/new_log.txt
    notify: Start docker
  
  handlers:
  - name:  Start docker
    apt:
       name: "{{pkg_name}}"
       state: present   