---
- name: Install docker,python3,docker-py,docker-compose
  hosts: all
  become: yes
  connection: ssh
  gather_facts: False
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Cache update
      yum: update_cache=yes cacheonly=yes

    - name: Install python3 and docker
      yum:
        name:
          - python3
          - docker
        state: present    

- name: Install docker-compose
  hosts: all
  become: yes
  connection: ssh
  tasks: 
    - name: check if docker-compose exists
      stat:
        path: /usr/local/bin/docker-compose
      register: file_check
    - name: Grab docker-compose bin if not exists
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{lookup('pipe','uname -s')}}-{{lookup('pipe','uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
      when: not file_check.stat.exists
    - name: install ansible dependency for Docker,Docker-compose using pip
      pip:
        name:
        - docker
        - docker-compose
        state: present

    - name: Add centos user to docker group
      user:
          name: centos
          groups: dockerroot
          append: true

    - name: Start docker
      systemd:
        name: docker
        state: started
      notify: docker.sock permission
  handlers:
    - name: docker.sock permission
      file:
        path: /var/run/docker.sock
        group: dockerroot

- name: Pull mongodb and mongo-express docker image
  hosts: all
  become: yes
  become_user: centos
  vars_files:
    - project-vars
  tasks:
  - name: Copy Docker compose file.
    copy:
      src: /home/karthik/Desktop/Devops/DevOps-BootCamp/ansible-practise/docker-compose.yaml
      dest: /home/centos
  - name: Docker login
    docker_login:
      registry_url: https://index.docker.io/v1/
      username: karthik0517
      password: "{{docker_password}}"
  - name: start container using docker compose
    docker_compose:
      project_src: /home/centos
      state: present