---
- name: Remove Docker 
  hosts: ec2_webserver
  become: true
  # become_method: sudo
  connection: ssh

  tasks:
  - name: Remove docker and its Components
    apt: 
      name: "{{ item }}"
      state: absent
    with_items:
    - docker-ce 
    - docker-ce-cli
    - containerd.io
  