apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: ansible-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: nginx-meta
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ngnix-service
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000

